---
  - name: Fail if OS is not RHEL
    assert: {{ ansible_lsb["id"] }} is "RedHatEnterpriseServer"
  
  - name: Fail if Puppet is installed
    command: "rpm -qa *puppet* && exit 1"

  - name: Fail if Java is present
    command: "which java && exit 1"

  - name: Fail if SELinux disabled
    command: "test $(getenforce) == 'Enforcing'" 

  - name: Confirm DNS resolution for localhost
    command: "ping -c1 localhost"

  - name: Confirm DNS resoultion for hostname
    command: "ping -c1 $(hostname -s)"

  - name: Confirm DNS resolution for hostname.domain
    command: "ping -c1 $(hostname -f)"

  - include: timesync-6.yml
    when: "{{ ansible_distribution_major_version }} == 6"

  - include: timesync-7.yml
    when: "{{ ansible_distribution_major_version }} == 7"
  
  ## Edit lines in this file to modify the firewall rules
  - include: firewall.yml

  ## comment this line out to skip recommended but not required packages
  - include: recommended-packages.yml

  ## Red Hat Subscription Manager settings - edit variables in vars, or change below
  # Register as user (joe_user) with password (somepass) 
  - name: Enable Satellite subscription via username/password
    redhat_subscription: 
      state: present 
      username: {{ rhn_user }} 
      password: {{ rhn_pass }} 
      pool: '^(Red Hat Enterprise Server|Red Hat Satellite)$'
    when: rhn_activationkey is unset

  # Register with activation key
  - name: Enable Satellite subscription via activation key
    redhat_subscription: 
      state: present 
      activationkey: {{ rhn_activationkey }} 
      pool: '^(Red Hat Enterprise Server|Red Hat Satellite)$'
    when: rhn_user and rhn_pass is unset

  - name: Reset enabled yum/rhn distros
    command: subscription-manager repos --disable "*"

  - name: Only enable required yum/rhn distros
    command: "subscription-manager repos \
      --enable rhel-{{ ansible_distribution_major_version }}-server-rpms \
      --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms \
      --enable rhel-6-server-satellite-{{ ansible_distribution_major_version }}.0-rpms"

  - name: Install Katello
    yum: name=katello state=installed

  - name: Copy answer file into place
    copy: role-ansible-satellite6-answers.yaml /etc/katello-installer

  - name: Enable answer file
    lineinfile: dest=/etc/katello-installer/katello-installer.yaml line=":answer_file: /etc/katello-installer/role-ansible-satellite6-answers.yaml"

  - name: Run katello installer
    comand: katello-installer
